[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
auto_detect_solc = true
fs_permissions = [{ access = "read", path = "./broadcast/"},{ access = "read", path = "./out/"}]

remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts","openzeppelin-contracts-08=lib/openzeppelin-contracts/contracts", "foundry-devops/src=lib/foundry-devops/src"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config